name: GitHub Pages CI

on:
  push:
    branches:
    - gh-pages

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          echo STAGE PAGES

  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses:
