name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: alpine:latest
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          apk update && apk add gcc make libc-dev
