name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Builder
        run: |
          sh patch.sh
          docker build --no-cache ./builder -t pnscan:latest
          docker images | grep pnscan:latest | egrep -o '[^ ]+$'
          mkdir backup && cd backup
          docker save pnscan:latest |tar -x && ls -la
#          docker image ls pnscan:latest
#          docker run --rm -t pnscan:latest
