name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Builder
        run: |
          sh patch.sh
          docker build --no-cache -f builder/Dockerfile -t pnscan:builder .
          docker image ls pnscan:builder
          sh check.sh
          docker build --no-cache -f builder/Dockerfile -t pnscan:latest .
          docker image ls pnscan:latest
#          docker run --rm -t pnscan:latest
