name: Main CI

on:
  push:
    branches: main

jobs:
  build:
    runs-on: Ubuntu-20.04
      steps:
        -
          uses: actions/checkout@v2
          id: checkout_
        -
          name: prepare
          run: ./prepare.sh
        -
          name: build
          run: docker build -f builder/Dockerfile -t pnscan:latest .

#docker image ls pnscan:latest
#docker run --rm -t pnscan:latest

