name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          cd builder && wget ftp://ftp.lysator.liu.se/pub/unix/pnscan/pnscan-1.11.tar.gz
          tar zxvf pnscan-1.11.tar.gz && cd pnscan-1.11 && make lnx && cd ..
          docker build -t pnscan:v1 .
          docker image ls pnscan:v1
