name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Builder
        run: |
          wget ftp://ftp.lysator.liu.se/pub/unix/pnscan/pnscan-1.11.tar.gz
          tar zxvf pnscan-1.11.tar.gz && rm -f pnscan-1.11.tar.gz
          cd pnscan-1.11 && cp {Makefile,bm.c,bm.h,ipsort,pnscan.c,version.c} ../builder
          cd .. && rm -rf pnscan-1.11
          cd builder && docker build . -t pnscan:latest
          ls -la && pwd
          docker image ls pnscan:latest
          docker run --rm -t pnscan:latest
