name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Builder
        run: |
          sh patch.sh
          docker build ./builder -t pnscan:latest
          ID=`docker images --format="{{.Repository}} {{.ID}}" |cut -d' ' -f2`
          docker image ls $ID
          docker run --rm -t $ID
