name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Builder
        run: |
          sh patch.sh
          docker rm $(docker ps -a -q)
          docker build ./builder -t pnscan:latest
          docker image ls pnscan:latest
          docker run --rm -t pnscan:latest
          docker save pnscan.tar
