name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Builder
        run: |
          sh patch.sh
          docker images ls
          docker build ./builder -t pnscan:latest
          ID=`docker images --format="{{.Repository}} {{.ID}}" |cut -d' ' -f2`
          DIGEST=`docker inspect --format='{{index .RepoDigests 0}}' pnscan:latest`
          docker image ls pnscan:latest
          docker run --rm -t pnscan:latest --name pnscan
