name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: Ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Builder
        run: |
          sh prepare.sh
          cd builder && docker build -t pnscan:latest .
          docker image ls pnscan:latest
          ls -la builder && pwd
          docker run --rm -t pnscan:latest nmap.scanme.org 10:30
          sh check.sh
