name: Main CI

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

#      - uses: azure/docker-login@v1
#        with:
#          login-server: ghcr.io
#          username: ${GITHUB_REPOSITORY_OWNER}
#          password: ${CONTAINER_TOKEN}

